    language: android
    jdk: oraclejdk8
    sudo: required
    android:
      components:
        - platform-tools
        - tools
        - build-tools-25.0.3
        - android-25
        - sys-img-armeabi-v7a-addon-google_apis-google-25
        - extra-android-m2repository
           # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - addon-google_apis-google-25

script:

- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"